server:
  port: 8081

spring:
  application:
    name: spring-config-client-01
  profiles:
    default: default
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      # url ?? :
      # http://localhost:8888/${name}/${profile}/${main}
      name: spring
      profile: default
      label: main

# ????? ???? Actuator ??
management:
  endpoints:
    web:
      exposure:
        include: "refresh"

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      name: spring
      profile: local


---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      profile: prod